//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiParking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public int IDBike { get; set; }
        public System.DateTime WriteOffDate { get; set; }
    
        public virtual Bike Bike { get; set; }
    }
}
